name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      apply:
        description: "Apply changes after plan"
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev   # This matches your GitHub Actions environment
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      TF_WORKSPACE: env-${{ github.event.inputs.environment }}

    steps:
      # 1. Checkout code
      - name: Checkout Repository 
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # 3. Show selected workspace
      - name: Show Selected Workspace
        run:  |
           echo "Using Terraform Cloud workspace: $TF_WORKSPACE"

      # 4. Terraform Format Check auto fix 
      - name: Terraform Format 
        run: terraform fmt -recursive

      
      - name: Debug Token
        run: |
          if [ -z "$TF_TOKEN_app_terraform_io" ]; then
            echo "❌ Token is missing!"
            exit 1
          else
            echo "✅ Token is set."
          fi


      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 6. Select or create workspace (prefix mode)
      - name: Select Workspace
        run: |
          terraform workspace select ${{ github.event.inputs.environment }} \
          || terraform workspace new ${{ github.event.inputs.environment }}

      # 7. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 8. Terraform Plan
      - name: Terraform Plan
        run: terraform plan \
          -var-file=environments/globals.tfvars \
          -var-file=environments/${{ github.event.inputs.environment }}.tfvars \
          -out=tfplan

      # 9. Upload Plan Artifact
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.event.inputs.environment }}
          path: tfplan

      # 10. Terraform Apply (only if checkbox is true)
      - name: Terraform Apply
        if: github.event.inputs.apply == 'true'
        run: terraform apply -auto-approve tfplan
